version: '3.8'

services:

  php:
    image: php:8.4-apache
    container_name: honey_php
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
    depends_on:
    - mysql
  mysql:
    image: mysql:8
    container_name: honey_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: honeygroup
      MYSQL_USER: honey
      MYSQL_PASSWORD: honeypass
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: honey_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      